vcom -reportprogress 30 -work work {hdl/address_decode_entity.vhd}
vcom -reportprogress 30 -work work {hdl/address_decode_tbl.vhd}
vcom -reportprogress 30 -work work {hdl/clock_divider_entity.vhd}
vcom -reportprogress 30 -work work {hdl/clock_divider_flow.vhd}
vcom -reportprogress 30 -work work {hdl/control_operation_entity.vhd}
vcom -reportprogress 30 -work work {hdl/control_operation_fsm.vhd}
vcom -reportprogress 30 -work work {hdl/cpu_interface_entity.vhd}
vcom -reportprogress 30 -work work {hdl/cpu_interface_intconx.vhd}
vcom -reportprogress 30 -work work {hdl/cpu_interface_struct.vhd}
vcom -reportprogress 30 -work work {hdl/status_registers_entity.vhd}
vcom -reportprogress 30 -work work {hdl/status_registers_spec.vhd}
vcom -reportprogress 30 -work work {hdl/tester_entity.vhd}
vcom -reportprogress 30 -work work {hdl/tester_flow.vhd}
vcom -reportprogress 30 -work work {hdl/xmit_rcv_control_entity.vhd}
vcom -reportprogress 30 -work work {hdl/xmit_rcv_control_fsm.vhd}
vcom -reportprogress 30 -work work {hdl/serial_interface_entity.vhd}
vcom -reportprogress 30 -work work {hdl/serial_interface_struct.vhd}
vcom -reportprogress 30 -work work {hdl/uart_top_entity.vhd}
vcom -reportprogress 30 -work work {hdl/uart_top_struct.vhd}
vcom -reportprogress 30 -work work {hdl/uart_tb_entity.vhd}
vcom -reportprogress 30 -work work {hdl/uart_tb_struct.vhd}
